// react-client/src/components/views/GameView.tsx
import { makeGuess } from '@/api/api';
import { useSignalR } from '@/context/SignalRContext';
import { FormEvent, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { useToast } from '../ui/use-toast';

type Props = { connectedUsers: string[]; messages: string[] };
const GameView = ({ connectedUsers, messages }: Props) => {
  const { hubConnection, userInfo } = useSignalR();
  const { toast } = useToast();
  const guessRef = useRef<HTMLInputElement>(null);
  const bottomLineRef = useRef<HTMLLIElement>(null);
  const [gameOverMessage, setGameOverMessage] = useState<string>('');

  const somebodyWon = useMemo(() => !!messages.find((el) => el.includes('wygrał grę z liczbą: ')), [messages]);
  const areControlsDisabled = connectedUsers.length < 2 || gameOverMessage.length > 0 || somebodyWon;

  const handleMakeGuess = async (e: FormEvent) => {
    e.preventDefault();
    if (!hubConnection || !guessRef.current || !userInfo) return;

    const guessNumber = +guessRef.current?.value.trim();

    if (guessNumber === undefined) {
      toast({ title: 'Wprowadź liczbę' });
      return;
    }
    await makeGuess(hubConnection, userInfo.roomName, userInfo.userName, guessNumber);
    guessRef.current.value = '';
  };

  const ReceivePrivateMessageListener = () => {
    if (!hubConnection || !userInfo) return;

    hubConnection.on('ReceivePrivateMessage', (userName: string, message: string) => {
      if (userName === userInfo.userName) {
        toast({ title: message });
      }
    });
  };
  const GameOverListener = () => {
    if (!hubConnection || !userInfo) return;

    hubConnection.on('GameOver', (userName: string, message: string) => {
      setGameOverMessage(message);
      if (userName === userInfo.userName) {
        toast({ title: 'Brawo! Wygrałeś grę!' });
      }
    });
  };
  const initializeListeners = () => {
    if (!hubConnection) return;

    ReceivePrivateMessageListener();
    GameOverListener();
  };

  useEffect(() => {
    initializeListeners();
  }, []);
  useLayoutEffect(() => {
    if (bottomLineRef.current) {
      console.log('scroll');
      bottomLineRef.current.scrollIntoView({
        behavior: 'instant',
      });
    }
  }, [messages]);

  if (!userInfo) return null;
  return (
    <div className="flex">
      <aside className="max-w-xs w-full bg-secondary p-4 flex flex-col gap-2 h-screen overflow-y-auto">
        <p>Pokój: {userInfo.roomName}</p>
        <p>Nazwa użytkownika: {userInfo.userName}</p>{' '}
        <section>
          <p>Zalogowani użytkownicy:</p>
          <ul className="list-decimal ml-6">
            {connectedUsers.map((user, index) => (
              <li key={index}>
                {user} {user === userInfo.userName && <span className="text-primary font-bold">(Ty)</span>}
              </li>
            ))}
          </ul>
        </section>
      </aside>
      <section className="w-full p-4 space-y-2 max-w-3xl mx-auto">
        <ul className="h-[calc(100vh-2rem-.5rem-3rem)] overflow-y-auto">
          <li>Czat:</li>
          {messages.map((msg, index) => (
            <li key={index} className="even:bg-secondary p-2 rounded">
              {msg}
            </li>
          ))}
          {(somebodyWon || gameOverMessage.length > 0) && (
            <li className="text-destructive font-bold p-2 bg-destructive/10 rounded">Gra została zakończona.</li>
          )}
          {connectedUsers.length < 2 && !gameOverMessage.length && !somebodyWon && (
            <li className="text-destructive font-bold p-2 bg-destructive/10 rounded">
              Oczekiwanie na drugiego gracza...
            </li>
          )}
          <li className="opacity-0" ref={bottomLineRef}>
            xd
          </li>
        </ul>
        <form onSubmit={handleMakeGuess} className="flex gap-2 h-12">
          <Input
            placeholder="Zgadnij liczbę"
            type="number"
            ref={guessRef}
            autoFocus
            disabled={areControlsDisabled}
            className="appearance-none"
            step={1}
            max={100}
            min={1}
          />
          <Button type="submit" disabled={areControlsDisabled}>
            Zgadnij
          </Button>
        </form>
      </section>
    </div>
  );
};

export default GameView;

// vue-client/src/components/GameView.vue
<script setup lang="ts">
import { useToast } from '@/components/ui/toast/use-toast'
import { useSignalRInvoke } from '@/signalR/connection'
import { useGameStore } from '@/stores/game-store'
import { storeToRefs } from 'pinia'
import { onUpdated, ref } from 'vue'
import { Button } from './ui/button'
import { Input } from './ui/input'

const { messages, roomName, userName, connectedUsers, gameOverMessage } =
  storeToRefs(useGameStore())
const { setUserInfo } = useGameStore()
const { execute: leaveRoomInvoke } = useSignalRInvoke('LeaveRoom')
const { execute: makeGuessInvoke } = useSignalRInvoke('MakeGuess', true)
const { toast } = useToast()

let somebodyWon = ref(!!messages?.value.find((el) => el.includes('wygrał grę z liczbą: ')))

// Chat
const bottomLineRef = ref<HTMLLIElement>()
const handleScrollToBottomOfChat = () => {
  bottomLineRef.value?.scrollIntoView({
    behavior: 'instant'
  })
}

// Form
const guessNumber = ref('')
function handleMakeGuess() {
  if (isInputDisabled()) {
    setUserInfo({
      roomName: '',
      userName: userName.value
    })
    return
  }
  const number = +guessNumber.value

  if (number === undefined) {
    toast({ title: 'Wprowadź liczbę' })
    return
  }
  makeGuessInvoke(roomName.value, userName.value, number)
  guessNumber.value = ''
}
const isInputDisabled = () =>
  connectedUsers.value.length < 2 || gameOverMessage.value.length > 0 || somebodyWon.value

// Automatyczny scroll na dół czatu
onUpdated(() => {
  handleScrollToBottomOfChat()
})

window.addEventListener('beforeunload', () => leaveRoomInvoke(roomName.value, userName.value))
</script>

<template>
  <div class="flex">
    <aside class="max-w-xs w-full bg-secondary p-4 flex flex-col gap-2 h-screen overflow-y-auto">
      <p>Pokój: {{ roomName }}</p>
      <p>Nazwa użytkownika: {{ userName }}</p>
      <section>
        <p>Zalogowani użytkownicy:</p>
        <ul class="list-decimal ml-6">
          <li v-for="user in connectedUsers">
            {{ user }}
            <span v-if="user === userName" class="text-primary font-bold">(Ty)</span>
          </li>
        </ul>
      </section>
    </aside>
    <section class="w-full p-4 space-y-2 max-w-3xl mx-auto">
      <ul class="h-[calc(100vh-2rem-.5rem-3rem)] overflow-y-auto">
        <li>Czat:</li>
        <li class="even:bg-secondary p-2 rounded" v-for="msg in messages">
          {{ msg }}
        </li>

        <!-- Gra zakończona -->
        <li
          v-if="somebodyWon || gameOverMessage.length > 0"
          class="text-destructive font-bold p-2 bg-destructive/10 rounded"
        >
          Gra została zakończona.
        </li>

        <!-- Oczekiwanie na gracza -->
        <li
          v-if="connectedUsers.length < 2 && !gameOverMessage.length && !somebodyWon"
          class="text-destructive font-bold p-2 bg-destructive/10 rounded"
        >
          Oczekiwanie na drugiego gracza...
        </li>
        <li class="opacity-0" ref="bottomLineRef">xd</li>
      </ul>
      <form @submit.prevent="handleMakeGuess" class="flex gap-2 h-12">
        <Input
          placeholder="Zgadnij liczbę"
          type="number"
          v-model="guessNumber"
          auto-focus="true"
          class="appearance-none"
          step="1"
          max="100"
          min="1"
        />
        <Button type="submit" :disabled="isInputDisabled()"> Zgadnij </Button>
      </form>
    </section>
  </div>
</template>
